import { slugify } from "./slug";

/**
 * P2-9: companies.slug is actually generated by a Postgres `BEFORE INSERT`
 * trigger (supabase/migrations/00042_companies_slug_trigger.sql), not app
 * code — see that migration's header for why. This file is a pure-TS
 * reference implementation of the SAME numeric-suffix collision-resolution
 * shape as that trigger, kept here purely so the algorithm has fast
 * unit-test coverage without spinning up Postgres. It is not wired into the
 * registration submit path — the trigger is authoritative at write time —
 * but is exported for any future admin/preview UI that wants to show an
 * applicant what their slug would look like.
 *
 * NOT byte-for-byte parity with the trigger's base-slug step, despite an
 * earlier version of this comment claiming otherwise (code-review finding,
 * 2026-08-27) — do not trust this as authoritative for what slug the
 * trigger will actually assign. `companySlugBase` normalizes accents via
 * `slug.ts`'s `.normalize("NFD")` + combining-mark strip, which only
 * decomposes PRECOMPOSED accented letters (é, ñ, ü, ç, ê, ...) — it covers
 * the French/Portuguese/Spanish/Vietnamese names this bilingual portal's
 * audience mostly uses. The trigger instead calls Postgres's `unaccent`
 * contrib extension, whose transliteration table also maps letters that
 * have NO NFD decomposition at all (they're distinct base letters, not a
 * base + combining mark): ß, Ø/ø, Æ/æ, Œ/œ, Ð/ð, Þ/þ and similar. For those,
 * `.normalize("NFD")` leaves the character untouched, `slugify`'s
 * `[^a-z0-9]` pass then strips it as punctuation, and the result silently
 * loses a letter instead of transliterating it:
 *   "Ørsted Ltd" -> TS "rsted-ltd"   vs SQL "orsted-ltd"
 *   "Weiß GmbH"  -> TS "wei-gmbh"    vs SQL "weiss-gmbh"
 * Full parity would mean porting Postgres's unaccent.rules transliteration
 * table into TS — real work for a class of company name this portal's
 * primary audience rarely uses. Pinning the known divergence in
 * company-slug.test.ts (rather than silently "fixing" only these two
 * examples) is the deliberate tradeoff: cheap now, and it fails loudly if
 * anyone ever mistakes this file for authoritative.
 */

/** Base slug for a company name, with the same id-based fallback the SQL
 *  trigger uses when the name yields nothing usable (e.g. all-punctuation,
 *  or a name in a script `slugify`'s [a-z0-9] pass strips entirely). */
export function companySlugBase(name: string, fallbackId: string): string {
  const base = slugify(name);
  return base || `company-${fallbackId.replace(/-/g, "")}`;
}

/**
 * Numeric-suffix collision resolution — same shape as the trigger's
 * `WHILE EXISTS (...) LOOP suffix := suffix + 1; ...` loop: the bare base
 * slug is tried first, then `-2`, `-3`, ... until one is free.
 */
export function resolveSlugCollision(
  base: string,
  existingSlugs: ReadonlySet<string>
): string {
  if (!existingSlugs.has(base)) return base;
  let suffix = 2;
  let candidate = `${base}-${suffix}`;
  while (existingSlugs.has(candidate)) {
    suffix += 1;
    candidate = `${base}-${suffix}`;
  }
  return candidate;
}

/** Convenience wrapper combining both steps, mirroring the trigger end-to-end. */
export function generateCompanySlug(
  name: string,
  fallbackId: string,
  existingSlugs: ReadonlySet<string>
): string {
  return resolveSlugCollision(companySlugBase(name, fallbackId), existingSlugs);
}
