import { writeFile } from "node:fs/promises";

export type AttributionEntry = {
  file: string;
  photographer: string;
  sourceUrl: string;
  license: string;
  fetchedAt: string;
};

export class AttributionLog {
  private entries = new Map<string, AttributionEntry>();
  constructor(private readonly path: string) {}

  async record(entry: AttributionEntry): Promise<void> {
    this.entries.set(entry.file, entry);
  }

  async flush(): Promise<void> {
    const byCategory = new Map<string, AttributionEntry[]>();
    for (const e of this.entries.values()) {
      const category = e.file.split("/")[0];
      const list = byCategory.get(category) ?? [];
      list.push(e);
      byCategory.set(category, list);
    }
    const lines: string[] = [
      "# Seed image attributions",
      "",
      "Generated by `scripts/seed-images/fetch.ts`. All photos sourced under the",
      "Unsplash License or Pexels License — free for commercial use, no attribution",
      "required. Photographers credited as courtesy.",
      "",
    ];
    for (const category of [...byCategory.keys()].sort()) {
      lines.push(`## ${category}`, "");
      const list = byCategory.get(category)!.sort((a, b) => a.file.localeCompare(b.file));
      for (const e of list) {
        lines.push(
          `- \`${e.file}\` — Photo by ${e.photographer} (${e.license}) — ${e.sourceUrl} — fetched ${e.fetchedAt}`
        );
      }
      lines.push("");
    }
    await writeFile(this.path, lines.join("\n"), "utf8");
  }
}
