"use server";

import { z } from "zod";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import {
  findPlan,
  formatPlanPrice,
  type PromotionPlanId,
} from "@/config/promotion-plans";

/**
 * Premium Local Partner application (customer design 12).
 *
 * Anonymous-friendly public intake. Both the hero "Apply for Premium
 * Membership" button and the "Book a Call" assistance band open the same
 * lightweight form (Full Name / Company / Email / Phone). We insert into
 * `business_requests` — NOT `premium_requests` — because the latter needs a
 * company_id FK and an authenticated owner, whereas this apply flow must accept
 * signed-out visitors. The row is written via the service-role client with
 * `submitter_id = auth user when signed in, NULL otherwise` (migration 00028
 * made the column nullable). Admins triage the lead at /admin/requests.
 *
 * The DB generates a human-readable `reference` (TIDRC-PR-YYYY-NNNNNN,
 * migration 00030) which we return so the UI can show a confirmation code.
 */

const FULL_NAME_MAX = 200;
const COMPANY_NAME_MAX = 200;
const EMAIL_MAX = 320;
const PHONE_MAX = 50;
const NOTE_MAX = 2000;

const PREMIUM_INTENT = "register_company" as const;
const PREMIUM_KIND = "business" as const;
/** Fallback when no plan is supplied (legacy callers). */
const DEFAULT_PLAN: PromotionPlanId = "congolese";

const applySchema = z.object({
  // Which promotion package the applicant chose. The price is derived
  // server-side from the plan and never taken from the client (00039).
  plan: z
    .enum(["congolese", "international", "international_strategic"])
    .default(DEFAULT_PLAN),
  fullName: z.string().trim().min(1).max(FULL_NAME_MAX),
  companyName: z.string().trim().min(1).max(COMPANY_NAME_MAX),
  email: z.string().trim().email().max(EMAIL_MAX),
  phone: z.string().trim().min(4).max(PHONE_MAX),
  note: z.string().trim().max(NOTE_MAX).optional().or(z.literal("")),
});

export type PremiumApplyInput = z.input<typeof applySchema>;

export interface PremiumApplyResult {
  ok: boolean;
  reference?: string;
  error?: "invalid" | "server";
}

export async function submitPremiumApplication(
  input: PremiumApplyInput
): Promise<PremiumApplyResult> {
  const parsed = applySchema.safeParse(input);
  if (!parsed.success) return { ok: false, error: "invalid" };
  const d = parsed.data;

  const supabase = await createServerSupabaseClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const plan = findPlan(d.plan) ?? findPlan(DEFAULT_PLAN)!;
  const base = `Promotion application — ${plan.id} (${formatPlanPrice(plan.amountUsd)}/year)`;
  const message = d.note ? `${base}\nNote: ${d.note}` : base;

  const admin = createAdminClient();
  const { data, error } = await admin
    .from("business_requests")
    .insert({
      submitter_id: user?.id ?? null,
      kind: PREMIUM_KIND,
      intent: PREMIUM_INTENT,
      full_name: d.fullName,
      company_name: d.companyName,
      email: d.email,
      phone: d.phone,
      message,
      promotion_plan: plan.id,
      promotion_amount_usd: plan.amountUsd,
    })
    .select()
    .single();

  if (error) {
    console.error("[submitPremiumApplication]", error.code, error.message);
    return { ok: false, error: "server" };
  }

  // `reference` (migration 00030, TIDRC-PR-YYYY-NNNNNN) is generated by the DB
  // default and returned by `.select()`. It is read through a cast because the
  // checked-in generated types can lag behind applied migrations (types are
  // regenerated separately after `supabase db push`).
  const reference = (data as unknown as { reference?: string | null } | null)
    ?.reference;

  return { ok: true, reference: reference ?? undefined };
}
