/**
 * Geographic option lists for trade-request forms.
 *
 * Country and province names are proper nouns kept as canonical English names
 * (a place name reads the same in every locale), so they live in config rather
 * than the i18n catalogs. COUNTRIES is the full ISO 3166 region set generated
 * via Intl.DisplayNames, with DRC trade partners hoisted to the top and a few
 * names overridden to match the app's stored values (see scripts/_gen_geo.cjs).
 */

/** Every country/territory; DRC + neighbours + key partners first, "Other" last. */
export const COUNTRIES = [
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Angola",
  "Zambia",
  "Rwanda",
  "Burundi",
  "Uganda",
  "Tanzania",
  "South Africa",
  "Kenya",
  "Nigeria",
  "Belgium",
  "France",
  "Germany",
  "United Kingdom",
  "Netherlands",
  "United States",
  "Canada",
  "China",
  "India",
  "United Arab Emirates",
  "Turkey",
  "Switzerland",
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Anguilla",
  "Antarctica",
  "Antigua & Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Ascension Island",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia & Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Cambodia",
  "Cameroon",
  "Canary Islands",
  "Cape Verde",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Central African Republic",
  "Ceuta & Melilla",
  "Chad",
  "Chile",
  "Christmas Island",
  "Clipperton Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Diego Garcia",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "European Union",
  "Eurozone",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard & McDonald Islands",
  "Honduras",
  "Hong Kong SAR China",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao SAR China",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Outlying Oceania",
  "Pakistan",
  "Palau",
  "Palestinian Territories",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Islands",
  "Poland",
  "Portugal",
  "Pseudo-Accents",
  "Pseudo-Bidi",
  "Puerto Rico",
  "Qatar",
  "Réunion",
  "Romania",
  "Russia",
  "Samoa",
  "San Marino",
  "São Tomé & Príncipe",
  "Sark",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Georgia & South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "St. Barthélemy",
  "St. Helena",
  "St. Kitts & Nevis",
  "St. Lucia",
  "St. Martin",
  "St. Pierre & Miquelon",
  "St. Vincent & Grenadines",
  "Sudan",
  "Suriname",
  "Svalbard & Jan Mayen",
  "Sweden",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad & Tobago",
  "Tristan da Cunha",
  "Tunisia",
  "Turkmenistan",
  "Turks & Caicos Islands",
  "Tuvalu",
  "U.S. Outlying Islands",
  "U.S. Virgin Islands",
  "Ukraine",
  "United Nations",
  "Unknown Region",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Wallis & Futuna",
  "Western Sahara",
  "Yemen",
  "Zimbabwe",
  "Other"
] as const;

/** DRC provinces / major cities for the "Preferred Location" select. */
export const DRC_PROVINCES = [
  "Kinshasa",
  "Lubumbashi",
  "Mbuji-Mayi",
  "Kananga",
  "Kisangani",
  "Bukavu",
  "Goma",
  "Matadi",
  "Kolwezi",
  "Likasi",
  "Tshikapa",
  "Boma",
  "Uvira",
  "Bunia",
  "Kindu"
] as const;

/** Canonical name of the home country — drives DRC-only fields in forms. */
export const HOME_COUNTRY = "Democratic Republic of the Congo";

/** Dial code paired with HOME_COUNTRY — the Congolese default. */
export const DEFAULT_DIAL_CODE = "+243";

/**
 * Dial code pre-selected when a country is chosen. Covers every entry in
 * COUNTRIES with its ITU E.164 country calling code (not an extended national
 * number — NANP members such as the US, Canada, and the Caribbean territories
 * all correctly share bare "+1", the UK/Crown Dependencies share "+44", etc.).
 * Keys must match the COUNTRIES strings byte for byte or the lookup silently
 * misses. A handful of uninhabited territories and non-country pseudo-entries
 * (Antarctica, Bouvet Island, Clipperton Island, European Union, Eurozone,
 * French Southern Territories, Heard & McDonald Islands, Outlying Oceania,
 * Pitcairn Islands, Pseudo-Accents, Pseudo-Bidi, U.S. Outlying Islands,
 * United Nations, Unknown Region, Other) have no genuine dial code and are
 * intentionally omitted — the country select still offers them, they just
 * never auto-fill a prefix.
 */
export const COUNTRY_DIAL_CODE: Readonly<Record<string, string>> = {
  [HOME_COUNTRY]: DEFAULT_DIAL_CODE,
  "Republic of the Congo": "+242",
  Angola: "+244",
  Zambia: "+260",
  Rwanda: "+250",
  Burundi: "+257",
  Uganda: "+256",
  Tanzania: "+255",
  "South Africa": "+27",
  Kenya: "+254",
  Nigeria: "+234",
  Belgium: "+32",
  France: "+33",
  Germany: "+49",
  "United Kingdom": "+44",
  Netherlands: "+31",
  "United States": "+1",
  Canada: "+1",
  China: "+86",
  India: "+91",
  "United Arab Emirates": "+971",
  Turkey: "+90",
  Switzerland: "+41",
  Afghanistan: "+93",
  "Åland Islands": "+358",
  Albania: "+355",
  Algeria: "+213",
  "American Samoa": "+1",
  Andorra: "+376",
  Anguilla: "+1",
  "Antigua & Barbuda": "+1",
  Argentina: "+54",
  Armenia: "+374",
  Aruba: "+297",
  "Ascension Island": "+247",
  Australia: "+61",
  Austria: "+43",
  Azerbaijan: "+994",
  Bahamas: "+1",
  Bahrain: "+973",
  Bangladesh: "+880",
  Barbados: "+1",
  Belarus: "+375",
  Belize: "+501",
  Benin: "+229",
  Bermuda: "+1",
  Bhutan: "+975",
  Bolivia: "+591",
  "Bosnia & Herzegovina": "+387",
  Botswana: "+267",
  Brazil: "+55",
  "British Indian Ocean Territory": "+246",
  "British Virgin Islands": "+1",
  Brunei: "+673",
  Bulgaria: "+359",
  "Burkina Faso": "+226",
  Cambodia: "+855",
  Cameroon: "+237",
  "Canary Islands": "+34",
  "Cape Verde": "+238",
  "Caribbean Netherlands": "+599",
  "Cayman Islands": "+1",
  "Central African Republic": "+236",
  "Ceuta & Melilla": "+34",
  Chad: "+235",
  Chile: "+56",
  "Christmas Island": "+61",
  "Cocos (Keeling) Islands": "+61",
  Colombia: "+57",
  Comoros: "+269",
  "Cook Islands": "+682",
  "Costa Rica": "+506",
  "Côte d’Ivoire": "+225",
  Croatia: "+385",
  Cuba: "+53",
  "Curaçao": "+599",
  Cyprus: "+357",
  Czechia: "+420",
  Denmark: "+45",
  "Diego Garcia": "+246",
  Djibouti: "+253",
  Dominica: "+1",
  "Dominican Republic": "+1",
  Ecuador: "+593",
  Egypt: "+20",
  "El Salvador": "+503",
  "Equatorial Guinea": "+240",
  Eritrea: "+291",
  Estonia: "+372",
  Eswatini: "+268",
  Ethiopia: "+251",
  "Falkland Islands": "+500",
  "Faroe Islands": "+298",
  Fiji: "+679",
  Finland: "+358",
  "French Guiana": "+594",
  "French Polynesia": "+689",
  Gabon: "+241",
  Gambia: "+220",
  Georgia: "+995",
  Ghana: "+233",
  Gibraltar: "+350",
  Greece: "+30",
  Greenland: "+299",
  Grenada: "+1",
  Guadeloupe: "+590",
  Guam: "+1",
  Guatemala: "+502",
  Guernsey: "+44",
  Guinea: "+224",
  "Guinea-Bissau": "+245",
  Guyana: "+592",
  Haiti: "+509",
  Honduras: "+504",
  "Hong Kong SAR China": "+852",
  Hungary: "+36",
  Iceland: "+354",
  Indonesia: "+62",
  Iran: "+98",
  Iraq: "+964",
  Ireland: "+353",
  "Isle of Man": "+44",
  Israel: "+972",
  Italy: "+39",
  Jamaica: "+1",
  Japan: "+81",
  Jersey: "+44",
  Jordan: "+962",
  Kazakhstan: "+7",
  Kiribati: "+686",
  Kosovo: "+383",
  Kuwait: "+965",
  Kyrgyzstan: "+996",
  Laos: "+856",
  Latvia: "+371",
  Lebanon: "+961",
  Lesotho: "+266",
  Liberia: "+231",
  Libya: "+218",
  Liechtenstein: "+423",
  Lithuania: "+370",
  Luxembourg: "+352",
  "Macao SAR China": "+853",
  Madagascar: "+261",
  Malawi: "+265",
  Malaysia: "+60",
  Maldives: "+960",
  Mali: "+223",
  Malta: "+356",
  "Marshall Islands": "+692",
  Martinique: "+596",
  Mauritania: "+222",
  Mauritius: "+230",
  Mayotte: "+262",
  Mexico: "+52",
  Micronesia: "+691",
  Moldova: "+373",
  Monaco: "+377",
  Mongolia: "+976",
  Montenegro: "+382",
  Montserrat: "+1",
  Morocco: "+212",
  Mozambique: "+258",
  "Myanmar (Burma)": "+95",
  Namibia: "+264",
  Nauru: "+674",
  Nepal: "+977",
  "New Caledonia": "+687",
  "New Zealand": "+64",
  Nicaragua: "+505",
  Niger: "+227",
  Niue: "+683",
  "Norfolk Island": "+672",
  "North Korea": "+850",
  "North Macedonia": "+389",
  "Northern Mariana Islands": "+1",
  Norway: "+47",
  Oman: "+968",
  Pakistan: "+92",
  Palau: "+680",
  "Palestinian Territories": "+970",
  Panama: "+507",
  "Papua New Guinea": "+675",
  Paraguay: "+595",
  Peru: "+51",
  Philippines: "+63",
  Poland: "+48",
  Portugal: "+351",
  "Puerto Rico": "+1",
  Qatar: "+974",
  "Réunion": "+262",
  Romania: "+40",
  Russia: "+7",
  Samoa: "+685",
  "San Marino": "+378",
  "São Tomé & Príncipe": "+239",
  Sark: "+44",
  "Saudi Arabia": "+966",
  Senegal: "+221",
  Serbia: "+381",
  Seychelles: "+248",
  "Sierra Leone": "+232",
  Singapore: "+65",
  "Sint Maarten": "+1",
  Slovakia: "+421",
  Slovenia: "+386",
  "Solomon Islands": "+677",
  Somalia: "+252",
  "South Georgia & South Sandwich Islands": "+500",
  "South Korea": "+82",
  "South Sudan": "+211",
  Spain: "+34",
  "Sri Lanka": "+94",
  "St. Barthélemy": "+590",
  "St. Helena": "+290",
  "St. Kitts & Nevis": "+1",
  "St. Lucia": "+1",
  "St. Martin": "+590",
  "St. Pierre & Miquelon": "+508",
  "St. Vincent & Grenadines": "+1",
  Sudan: "+249",
  Suriname: "+597",
  "Svalbard & Jan Mayen": "+47",
  Sweden: "+46",
  Syria: "+963",
  Taiwan: "+886",
  Tajikistan: "+992",
  Thailand: "+66",
  "Timor-Leste": "+670",
  Togo: "+228",
  Tokelau: "+690",
  Tonga: "+676",
  "Trinidad & Tobago": "+1",
  "Tristan da Cunha": "+290",
  Tunisia: "+216",
  Turkmenistan: "+993",
  "Turks & Caicos Islands": "+1",
  Tuvalu: "+688",
  "U.S. Virgin Islands": "+1",
  Ukraine: "+380",
  Uruguay: "+598",
  Uzbekistan: "+998",
  Vanuatu: "+678",
  "Vatican City": "+379",
  Venezuela: "+58",
  Vietnam: "+84",
  "Wallis & Futuna": "+681",
  "Western Sahara": "+212",
  Yemen: "+967",
  Zimbabwe: "+263",
};

/**
 * Dial codes offered in phone fields. Derived from COUNTRY_DIAL_CODE so the
 * dropdown can never be narrower than the country map — de-duplicated (several
 * countries share a code, e.g. +1, +7, +44, +61) and sorted numerically, with
 * DRC's own code pinned first since it's the home country default.
 */
export const DIAL_CODES: readonly string[] = [
  DEFAULT_DIAL_CODE,
  ...[...new Set(Object.values(COUNTRY_DIAL_CODE))]
    .filter((code) => code !== DEFAULT_DIAL_CODE)
    .sort((a, b) => Number(a.slice(1)) - Number(b.slice(1))),
];
